<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tambah Baru</name>
   <tag></tag>
   <elementGuidId>f26d9874-e3e9-42d6-8c07-7d5f4d885480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAddGlobal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAddGlobal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0dc3319d-8a59-45e1-b4d8-cd2c2e1deba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddGlobal</value>
      <webElementGuid>f113c65b-aff3-435e-b857-05c7a5c0ef34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>5a5d8079-ba7c-42c8-a344-36401f085622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn blue btn-outline btn-circle btn-sm</value>
      <webElementGuid>d3822e29-6405-4d74-868a-6e0df5b2a0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Baru </value>
      <webElementGuid>efb9454b-514c-4659-afda-c260db8704e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddGlobal&quot;)</value>
      <webElementGuid>37acc303-7cb4-4238-8b87-7ad2a5d04691</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnAddGlobal']</value>
      <webElementGuid>a27aaec2-9bca-4f47-b74f-1879fa566ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_HeaderContainer']/div/div/div[3]/table/tbody/tr/td[2]/div/div/div/div/a</value>
      <webElementGuid>34612b8d-abb9-4aa1-8d6d-8bea6dabea22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tambah Baru')]</value>
      <webElementGuid>24b731d2-a7b0-4f67-b09e-50899d7833fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaya Umum'])[3]/following::a[1]</value>
      <webElementGuid>1a868b39-450e-4b31-b141-1f7d0e711b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Mutakhir'])[1]/preceding::a[1]</value>
      <webElementGuid>4ac3d103-defe-4f12-8093-f13c402477c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Baru']/parent::*</value>
      <webElementGuid>f09dcbdd-ec01-43cf-8424-3e3e2a13f2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[6]</value>
      <webElementGuid>0e1d3202-f258-41e5-a550-6c6af2ae97ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/a</value>
      <webElementGuid>7ba961c4-ef2b-42ac-a626-5f032fa2a201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnAddGlobal' and @href = 'javascript:;' and (text() = 'Tambah Baru ' or . = 'Tambah Baru ')]</value>
      <webElementGuid>903f05b8-6dae-41bd-83ea-ef0992edf203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
