<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Pilih Rap</name>
   <tag></tag>
   <elementGuidId>77187c93-5466-41af-ad6f-80ee97ab68f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='jqg2_btnViewRAP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg2_btnViewRAP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c3d433d-5875-41b4-a5ec-d3414eaf65cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn red btn-outline</value>
      <webElementGuid>2099543d-8e27-47e2-8dbf-64911e19879b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_btnViewRAP</value>
      <webElementGuid>2706865c-4529-4a19-92f1-bec2cfa6edeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TryOpenRapViewer('Kode_RAP_jqg2',null,false,'jqg2');</value>
      <webElementGuid>ab56cc1a-41e8-4917-8078-692f1d03f146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih Rap</value>
      <webElementGuid>e2c3fccc-8b84-4f07-9055-462c7c97a24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_btnViewRAP&quot;)</value>
      <webElementGuid>bf738994-215a-4ed3-b087-c453890c76cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='jqg2_btnViewRAP']</value>
      <webElementGuid>3bdc4266-0983-4923-a16f-95f979e5ae13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jqg2_dvNamaRAP']/div/div/div[2]/button</value>
      <webElementGuid>80f981fb-c7ae-4a66-b0a6-d1e738f1441f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAP :'])[1]/following::button[1]</value>
      <webElementGuid>8da531a6-d3a9-49f9-8852-a8b4a16a36d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan Detil :'])[1]/following::button[1]</value>
      <webElementGuid>1360b982-5e85-489d-a5eb-3fef30708762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sisa RAP :'])[1]/preceding::button[1]</value>
      <webElementGuid>b3b3491f-fccb-4075-9256-d6c24a535622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Rap']/parent::*</value>
      <webElementGuid>4a5bba6f-542b-468a-905b-3cfe663e0c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/button</value>
      <webElementGuid>7df7bea9-1606-4ffb-951d-1f87bc3530fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'jqg2_btnViewRAP' and (text() = ' Pilih Rap' or . = ' Pilih Rap')]</value>
      <webElementGuid>25cf20e9-ec98-4ddd-97bb-7b1523ba6bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
