<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Menu_Search</name>
   <tag></tag>
   <elementGuidId>eac278ff-2ea2-490b-be39-66966d0f6073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filterMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filterMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>888ec05f-b95e-40c2-bc07-a4837e9dcbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterMenu</value>
      <webElementGuid>62192c7e-634a-4e0a-815e-999af977c5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2bf8eaa-4d75-4941-9174-17badb5f9dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>47b6287e-988d-4068-924e-398b82427c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control no-padding-hr</value>
      <webElementGuid>050b76d4-ff35-4bd0-85b7-8dd59137ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterMenu&quot;)</value>
      <webElementGuid>ff73e69c-7db1-43ba-a58d-514c82a3054e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filterMenu']</value>
      <webElementGuid>41060cdc-f509-4b16-90f7-04582aa691d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu-inner']/div[2]/input</value>
      <webElementGuid>9475eb41-9446-4e61-859e-5625437fbb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ce42e9dd-3da3-4862-82f9-976261cdc342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filterMenu' and @type = 'text' and @placeholder = 'Search...']</value>
      <webElementGuid>7442b24c-a361-4b2b-9cd6-8c47e30ced0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
