<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Main_Kode_Proyek</name>
   <tag></tag>
   <elementGuidId>9fdf7290-7386-43c5-a485-091f9a60f95a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proyekSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='proyekSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17e0afba-1b43-4f78-a19f-78ca3b01443b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proyekSelect</value>
      <webElementGuid>059a67eb-8fc5-4015-b421-dfffab9cf85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>511c21ee-1821-4ce9-9063-297f8b16b5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>a76af321-5c4f-4cd2-b545-6ef88b1156c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>d393f656-9e19-4962-b2ef-a758e73c04c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0000 - TOWER MOO</value>
      <webElementGuid>c11869e3-f1bd-45c0-9b26-cb7d86d9baf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proyekSelect&quot;)</value>
      <webElementGuid>e436c795-39a4-47f5-80fd-ee3f7ed9f3d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='proyekSelect']</value>
      <webElementGuid>70ca8b75-7b5a-4e99-8f5e-ba9b3c8fd777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-navbar-collapse']/div/ul/li/a</value>
      <webElementGuid>6ed44a24-ed16-474f-99d0-c113351a9477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIDE MENU'])[1]/following::a[2]</value>
      <webElementGuid>e7f3de8e-9657-4a19-b539-be14a48b86a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='set as default'])[1]/preceding::a[1]</value>
      <webElementGuid>79a071f8-40e9-4fd5-b445-a04c44fda4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0000 -']/parent::*</value>
      <webElementGuid>4b145ba1-a27d-4b5e-ac16-b4b257433ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>ee6818bd-a609-468e-9106-a82fccca193f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>36a1c30d-ce41-45b0-87ea-0af85e9b2f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'proyekSelect' and @href = '#' and (text() = '0000 - TOWER MOO' or . = '0000 - TOWER MOO')]</value>
      <webElementGuid>e445fa97-fbd7-4b87-8fab-dd98acc54d65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
