<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih_Rap</name>
   <tag></tag>
   <elementGuidId>10ba654e-153c-489d-b12b-a1b2add30d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rap-checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rap-checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74926de8-d004-4d3d-8d94-6d3ee609aa87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6482aefa-2539-45e7-ad89-e21cda2ec2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RAPradio</value>
      <webElementGuid>f2776c2a-a316-46e1-a1a3-5929a6b53e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rap-checkbox1</value>
      <webElementGuid>f0a7eb36-5304-4d4d-83c5-1c09c98057a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RAPCbClick(this)</value>
      <webElementGuid>9d925801-aaaa-4b70-9ea7-168f989b7827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rap-checkbox</value>
      <webElementGuid>8c9fe96f-8e74-4142-a851-79e57f8e8221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>22B0106.001</value>
      <webElementGuid>f1d3e347-f5c2-456c-9f70-9807ff96513b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rap-checkbox1&quot;)</value>
      <webElementGuid>d35922e7-9b47-4071-83f8-027025b37b87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rap-checkbox1']</value>
      <webElementGuid>12269d8e-9bcc-49e9-855e-4684fa46622d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[9]/input</value>
      <webElementGuid>e6e60713-00d6-46b6-97bd-d84a4ab24c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input</value>
      <webElementGuid>bc1aea19-7100-4e67-9cf9-e41e11f01e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'RAPradio' and @id = 'rap-checkbox1']</value>
      <webElementGuid>675223a3-e3f5-4371-be66-139e1c118795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
