<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_btn_Menyetujui</name>
   <tag></tag>
   <elementGuidId>18b32737-6a5f-4c7a-a131-3c61b4a6a479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='APV_mod_Approve']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#APV_mod_Approve</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be77c498-3469-4866-abc6-cbac3b04daf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>APV_mod_Approve</value>
      <webElementGuid>2a47c1eb-f8a4-441e-96e4-4c9c5e5f6a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>587d8a6b-a0ff-436f-9e78-cfa356b8cef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>c3330596-f6b1-47c3-9808-e98743b09d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menyetujui</value>
      <webElementGuid>3dd742ea-e6de-4489-a921-dd5ad2c38a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APV_mod_Approve&quot;)</value>
      <webElementGuid>77ab1183-2d19-45f9-b272-1e3625a2f057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='APV_mod_Approve']</value>
      <webElementGuid>9da6a915-cbd6-4a56-8bf4-5094bc51c184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APV_Modal_Edit']/div/div/div[3]/button[3]</value>
      <webElementGuid>1f062ac7-7a7c-4ed4-ab57-3872b12d3fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menolak'])[1]/following::button[1]</value>
      <webElementGuid>c31bd604-8d80-4157-854a-a32ef88ad72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menyetujui']/parent::*</value>
      <webElementGuid>1c9b7588-00e5-4b51-a591-f9098f632e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[3]</value>
      <webElementGuid>da6986fd-d9bc-44ac-b493-574dc9683e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'APV_mod_Approve' and (text() = 'Menyetujui' or . = 'Menyetujui')]</value>
      <webElementGuid>547f62d5-60a3-47bf-b43b-d81fabce5b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
