<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Alasan_Menolak_or_Menyetujui</name>
   <tag></tag>
   <elementGuidId>65435b61-9804-42a6-9ea7-d0b790f55332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='APV_mod_Reason']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#APV_mod_Reason</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>472c82cf-22e2-4142-b07e-eb6e8ddbb605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>APV_mod_Reason</value>
      <webElementGuid>463e25bf-4c72-4099-9d95-fed88a9d3b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>64d2ec9a-6360-4d2d-beb5-ff8f8ac3240a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>39</value>
      <webElementGuid>b118b5f8-774c-46f8-98c8-bf6f5d5b7467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Silahkan tulisan alasan</value>
      <webElementGuid>4d894903-7db6-44c9-8803-6da4530cec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APV_mod_Reason&quot;)</value>
      <webElementGuid>d36494d9-3785-476b-995b-0eb1ef2571da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='APV_mod_Reason']</value>
      <webElementGuid>e6f3a51c-21c8-4b7b-9959-bc1231372e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APV_Modal_Edit']/div/div/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>b532b6db-8795-41b1-9cbd-c2f05a85618f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>6b904785-99f2-4b7d-832e-6956111e511d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'APV_mod_Reason' and @placeholder = 'Silahkan tulisan alasan']</value>
      <webElementGuid>45b2a131-d2ed-4826-884f-c27206fd3a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
