<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_btn_Menolak</name>
   <tag></tag>
   <elementGuidId>44949c54-c391-4a8e-9d80-33942924c576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='APV_mod_Reject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#APV_mod_Reject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6d6c43b-45f5-454c-b14a-256a16e8fd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>APV_mod_Reject</value>
      <webElementGuid>1b7fe312-761a-4e73-bcb8-9f209da53ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn red</value>
      <webElementGuid>aea136a5-9b9d-42c1-a71d-6ccb67d63f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>267704b9-f364-406b-9e43-b5103473c467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menolak</value>
      <webElementGuid>ac093ae8-7b5a-4d8a-8bb5-b4fcbc216d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APV_mod_Reject&quot;)</value>
      <webElementGuid>40c10001-1f2e-4cf1-9bf8-87c2f8fb9523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='APV_mod_Reject']</value>
      <webElementGuid>c0208588-a94e-4372-b1e2-fc0025f3331f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APV_Modal_Edit']/div/div/div[3]/button[2]</value>
      <webElementGuid>e607d55f-2458-4d93-97d5-27f53f4c6a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda akan menolak transaksi ini'])[1]/following::button[2]</value>
      <webElementGuid>27401e5e-588c-49ab-ac3d-ba35c0aaaaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menyetujui'])[1]/preceding::button[1]</value>
      <webElementGuid>212916d8-ff44-44b2-acfb-1361e19a05d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menolak']/parent::*</value>
      <webElementGuid>13b04282-cfb1-4da1-9621-febb6d3b861f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[3]/button[2]</value>
      <webElementGuid>3031caad-7e94-4766-b455-74eace83bcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'APV_mod_Reject' and (text() = 'Menolak' or . = 'Menolak')]</value>
      <webElementGuid>dcdc50c7-38ca-4cb2-8c2b-8610f77187aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
