<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_btn_Batal</name>
   <tag></tag>
   <elementGuidId>880d4f76-4056-4eb7-aeab-299a0e4b5e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='APV_Modal_Edit']/div/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-dialog.drag.ui-draggable > div.modal-content > div.modal-footer > button.btn.dark.btn-outline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>227d640f-6ab7-44fd-ad74-61d340152dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dark btn-outline</value>
      <webElementGuid>3bf3760b-b2e7-4fe0-b31c-9195e3f1d1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>c0a46291-af0c-4548-b825-6ec2bac9732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>78501a5a-6fa4-42ea-ae0f-b0724f3f9921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batal</value>
      <webElementGuid>f6444f86-2e7b-47c5-8838-c9752e5588f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APV_Modal_Edit&quot;)/div[@class=&quot;modal-dialog drag ui-draggable&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn dark btn-outline&quot;]</value>
      <webElementGuid>71267471-2780-40e5-8b98-68715ed0b268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APV_Modal_Edit']/div/div/div[3]/button</value>
      <webElementGuid>ff90c44d-36c4-4461-8303-5c50baae37d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda akan menolak transaksi ini'])[1]/following::button[1]</value>
      <webElementGuid>10cd3f33-0461-4606-9c40-2975fda8c4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menolak'])[1]/preceding::button[1]</value>
      <webElementGuid>386bf9df-a842-4d22-be07-43e92f848a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menyetujui'])[1]/preceding::button[2]</value>
      <webElementGuid>7ae17f7d-c2f0-4219-b51d-b52a71f27867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[3]/button</value>
      <webElementGuid>068432cf-5f42-45de-8fe2-9d90c6944021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Batal' or . = 'Batal')]</value>
      <webElementGuid>1d6d2f8f-b0f3-4195-b1fb-bd7f0cfcf1c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
