<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Asuransi</name>
   <tag></tag>
   <elementGuidId>b746eac3-789b-43b5-b43a-115fff03b4b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[.='Asuransi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.mmc-dropdown-delay.animated.fadeInLeft > li.mm-dropdown.open > ul > li > a > span.mm-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7780a44b-ab87-4b43-9f55-570e7325bbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mm-text</value>
      <webElementGuid>477c56e7-e096-4ede-a806-74540a0259ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asuransi</value>
      <webElementGuid>e140634f-8ace-4221-85f1-69aa05dbc11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoreMenu&quot;)/li[@class=&quot;mm-dropdown mm-dropdown-root open&quot;]/ul[@class=&quot;mmc-dropdown-delay animated fadeInLeft&quot;]/li[@class=&quot;mm-dropdown open&quot;]/ul[1]/li[1]/a[1]/span[@class=&quot;mm-text&quot;]</value>
      <webElementGuid>12516f07-7dc0-4dc6-bc16-2bad2ca1b9be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CoreMenu']/li[6]/ul/li/ul/li/a/span</value>
      <webElementGuid>9813526b-1f34-4128-b649-9d1f82e9a6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[3]/following::span[1]</value>
      <webElementGuid>5981b265-d03f-4bae-ad8c-29c639c602d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Garansi'])[1]/following::span[2]</value>
      <webElementGuid>d57a6770-d506-4bc4-bbdd-83ae20360de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fasilitas'])[1]/preceding::span[1]</value>
      <webElementGuid>625c42f9-16d1-474c-9b3a-1a99f7347df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi Pusat'])[1]/preceding::span[2]</value>
      <webElementGuid>8a371157-8f6f-4045-b99a-20bb4bc14188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asuransi']/parent::*</value>
      <webElementGuid>90fc0e30-40f1-4d31-9388-d169a6310e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/ul/li/a/span</value>
      <webElementGuid>dc8031b4-4a90-4d92-a0a6-490beb1592c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Asuransi' or . = 'Asuransi')]</value>
      <webElementGuid>9e238bcd-cd2a-47e7-9381-738c01eca913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
