<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Asuransi</name>
   <tag></tag>
   <elementGuidId>b746eac3-789b-43b5-b43a-115fff03b4b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.mmc-dropdown-delay.animated.fadeInLeft > li.mm-dropdown.open > ul > li > a > span.mm-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='CoreMenu']/li[6]/ul/li/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc58f11f-e7e6-444d-afd3-cf56fb8678bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mm-text</value>
      <webElementGuid>7090b73e-1e9c-419c-9185-d174830a79f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asuransi</value>
      <webElementGuid>00892a06-63fe-46a1-aa37-a7f6043e613e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoreMenu&quot;)/li[@class=&quot;mm-dropdown mm-dropdown-root open&quot;]/ul[@class=&quot;mmc-dropdown-delay animated fadeInLeft&quot;]/li[@class=&quot;mm-dropdown open&quot;]/ul[1]/li[1]/a[1]/span[@class=&quot;mm-text&quot;]</value>
      <webElementGuid>635aaabd-8293-4aa5-a3e3-05e109a7c798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CoreMenu']/li[6]/ul/li/ul/li/a/span</value>
      <webElementGuid>64e3750c-5f1d-4834-8a30-fd8d01e40709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[3]/following::span[1]</value>
      <webElementGuid>fc88a7a9-2917-408a-831b-f6088d985abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Garansi'])[1]/following::span[2]</value>
      <webElementGuid>60969055-9843-405a-a130-be22b2c0b5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fasilitas'])[1]/preceding::span[1]</value>
      <webElementGuid>54e7ad69-225f-495a-b4c4-c7ffa53b690b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaksi Pusat'])[1]/preceding::span[2]</value>
      <webElementGuid>32ddae20-8f95-4714-bee0-6b2660675191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asuransi']/parent::*</value>
      <webElementGuid>2cfabde8-85d2-47cd-9318-1146c96d1d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/ul/li/a/span</value>
      <webElementGuid>e81a2bb2-c747-4ad7-a74e-709ba0d6aa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Asuransi' or . = 'Asuransi')]</value>
      <webElementGuid>44c09db7-d6c1-402b-afc1-8ad6a30ebb96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
