<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transaction</name>
   <tag></tag>
   <elementGuidId>199f5c64-83a6-4f35-b50b-af1df9030983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[.='Transaction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.mm-dropdown.mm-dropdown-root.open > ul.mmc-dropdown-delay.animated.fadeInLeft > li.mm-dropdown > a > span.mm-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'mm-text' and (text() = 'Transaction' or . = 'Transaction')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51d616c9-aa25-44a6-905c-7e3bf013e207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mm-text</value>
      <webElementGuid>8cc6a6aa-8edb-41a9-bd6f-acef4f116728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transaction</value>
      <webElementGuid>78650d4d-d585-4af6-a104-10bba874a6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoreMenu&quot;)/li[@class=&quot;mm-dropdown mm-dropdown-root open&quot;]/ul[@class=&quot;mmc-dropdown-delay animated fadeInLeft&quot;]/li[@class=&quot;mm-dropdown&quot;]/a[1]/span[@class=&quot;mm-text&quot;]</value>
      <webElementGuid>9bed477f-93e1-47df-b01b-91d5fe434ccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CoreMenu']/li[10]/ul/li/a/span</value>
      <webElementGuid>79330360-5f15-48fa-9f39-e76d3430063c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Management'])[1]/following::span[1]</value>
      <webElementGuid>715330fd-824c-4c2e-846b-88897eaf80a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Resource Monitoring'])[1]/following::span[2]</value>
      <webElementGuid>515eb5c9-769f-45ea-a851-471a7dedae09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Cash'])[1]/preceding::span[1]</value>
      <webElementGuid>71d03592-9c1c-408f-9d5a-ae3fb5783062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pertanggungjawaban Pinjaman'])[1]/preceding::span[2]</value>
      <webElementGuid>bbe8f214-38b5-40ec-8b74-0f989261d12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/ul/li/a/span</value>
      <webElementGuid>42f8cd9d-2cb9-43e5-8cbe-3259f1eb1401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transaction' or . = 'Transaction')]</value>
      <webElementGuid>ba027e8a-e667-4066-9aee-2e357afcfebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
