<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Asuransi_AktifNonAktif</name>
   <tag></tag>
   <elementGuidId>04de7cba-c337-42bd-9353-0fad68269b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3_status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='3_status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>80e722be-8bab-4aa4-90d0-37c66d0192d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3_status</value>
      <webElementGuid>bfcbb50e-57a7-4011-9c8a-d4db6d1f8270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>defvalue</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>ed5b5e8e-7826-4d5c-840e-ba796eb530df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-check</value>
      <webElementGuid>e23fcd06-549f-411c-8129-9f9e69ff05a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>UbahStatus(3,'True');</value>
      <webElementGuid>c43f001b-ad75-4aaa-aa96-e2117abe3228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3_status&quot;)</value>
      <webElementGuid>9a6b6f47-9922-48b7-87ee-cf2913109c23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='3_status']</value>
      <webElementGuid>53b291f1-f34e-4689-aa79-736f83e821c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='3']/td[3]/span</value>
      <webElementGuid>204def75-0cdf-4abd-8aae-8281703fb644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/span</value>
      <webElementGuid>a86543eb-885d-49ba-a913-67faf54c4590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '3_status']</value>
      <webElementGuid>e144d2e9-9479-4b20-974b-c8203d2f6ee1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
