<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Save</name>
   <tag></tag>
   <elementGuidId>36423d59-0627-48ef-986f-b2bcf176deb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.btn-label.icon.fa.fa-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnSaveGlobal']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a13d2644-794e-40db-b352-1f1652c70463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-label icon fa fa-save</value>
      <webElementGuid>1b46aa10-1027-40cb-bba3-bfa37fad8b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveGlobal&quot;)/span[@class=&quot;btn-label icon fa fa-save&quot;]</value>
      <webElementGuid>2637cc65-666f-466f-89ed-ea1c31a3a989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btnSaveGlobal']/span</value>
      <webElementGuid>ab481619-54c0-4298-bdcd-f0c479cac869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>aa557510-7add-4503-a6fc-314118389572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
