<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fasilitas_Button_Cancel</name>
   <tag></tag>
   <elementGuidId>d326febc-782c-4506-ab93-7dbc6de27273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3_cancelIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='3_cancelIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5820faba-7e5f-4465-b2a9-c3aacff3e81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3_cancelIcon</value>
      <webElementGuid>1b03a95c-c3b6-4815-a92a-13d20b48268a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-reply</value>
      <webElementGuid>1aa19eab-3c3d-4dd7-9c72-8c2218849285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CancelRow(3);return false;</value>
      <webElementGuid>762c498d-2379-405f-a8af-62098c143dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3_cancelIcon&quot;)</value>
      <webElementGuid>42dc9c1a-6982-45d6-972c-eb00c02c8d8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='3_cancelIcon']</value>
      <webElementGuid>38317444-d67a-4565-9799-0efeb7e13af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='3']/td[5]/span[2]</value>
      <webElementGuid>2f659d24-b2a5-4c16-a582-a5139f30a83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/span[2]</value>
      <webElementGuid>95ca0cf0-236b-4798-bc8e-9be0090c394e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '3_cancelIcon']</value>
      <webElementGuid>9e36dedc-5b06-4654-9c98-290c4d8724e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
