<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fasilitas_Button_Edit</name>
   <tag></tag>
   <elementGuidId>48ff8846-6ceb-4cdf-8369-f47ee9a4d607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3_editIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='3_editIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>88236ed0-c3b4-48d6-9640-afd2e354f064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3_editIcon</value>
      <webElementGuid>9d80b02a-ad74-46aa-a253-86adb973d91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-pencil-square-o </value>
      <webElementGuid>f068e1d5-9fca-4078-bea5-9eff47a9e12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RowEdit(3);return false;</value>
      <webElementGuid>e6d43ed0-3587-46e1-bbe2-e439b6ac446f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3_editIcon&quot;)</value>
      <webElementGuid>9e7e2cd7-c962-496d-9c32-426729d19a8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='3_editIcon']</value>
      <webElementGuid>896d16cf-de49-47af-860d-26d54a59ac44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='3']/td[5]/span</value>
      <webElementGuid>66a6e2b1-1807-4aa6-9bc6-a2f7417c8850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/span</value>
      <webElementGuid>678e9035-35d0-4a2f-bed2-e889222e4657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '3_editIcon']</value>
      <webElementGuid>05bccd22-8bb8-4de4-995d-09ce774265f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
