<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Input_Kd_Fasilitas</name>
   <tag></tag>
   <elementGuidId>fc6639b1-970b-44ff-85f8-a3188582b3cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Nama_Fasilitas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Nama_Fasilitas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbffe161-8973-4a59-90c7-285c699c936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>450061bf-4694-4de9-afc8-d12e77c6e135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nama_Fasilitas</value>
      <webElementGuid>4b8c3f95-5504-4239-b495-f5acdaa9b679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Nama_Fasilitas</value>
      <webElementGuid>25045245-5259-4515-9b47-cd8fc480e1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Nama_Fasilitas&quot;)</value>
      <webElementGuid>2e6c9acf-8e2e-439e-9b29-ff904d2df32a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Nama_Fasilitas']</value>
      <webElementGuid>e797cb22-d522-4a57-9a7f-8c5df1d17dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>625a44ff-1264-45e4-ad46-3b1456b8571b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f5aae9d1-5a11-4425-b9ed-e1c90672ec3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Nama_Fasilitas' and @id = 'gs_Nama_Fasilitas']</value>
      <webElementGuid>f9349133-ea83-4cfb-aeee-8dc5aa84efd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
