<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_DDL_Status</name>
   <tag></tag>
   <elementGuidId>4c283cd3-fc0b-40a3-a2bd-a316cc8410b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gs_Status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e38a5d20-ae55-409f-bc35-f5d5b3dc7a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>ca53d177-328f-4561-bbbd-6a3e5d75a007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Status</value>
      <webElementGuid>e1b56949-a144-41ed-841b-fc1786da550f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[All]AktifNon Aktif</value>
      <webElementGuid>e368bdd4-478b-4d35-b09d-bcd1c5aa9773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Status&quot;)</value>
      <webElementGuid>9be6eb1e-7057-4423-ab7f-902fac7a8ce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gs_Status']</value>
      <webElementGuid>cd115be0-3115-449c-b14a-d00e8c04fac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[3]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>34b1d4b6-25ed-420f-9e54-2f837a3f4b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[1]/following::select[1]</value>
      <webElementGuid>de6b1ca9-de9d-455d-94f5-b8bbd209d554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kd_Asuransi'])[1]/following::select[1]</value>
      <webElementGuid>f0de184c-9383-4df7-8f13-9cd1a17e6e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[2]/preceding::select[1]</value>
      <webElementGuid>4f9197ee-d30d-4568-a33f-be42664111bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[3]/preceding::select[1]</value>
      <webElementGuid>3dff6e26-a45f-4c8f-a7cd-1cd2969104bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>393d74dd-4a2b-49bb-9446-78dbcfdef950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Status' and @id = 'gs_Status' and (text() = '[All]AktifNon Aktif' or . = '[All]AktifNon Aktif')]</value>
      <webElementGuid>c7d5eadb-cef0-46d0-8004-b8726bf3daf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
