<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Input_Kd_Asuransi</name>
   <tag></tag>
   <elementGuidId>d35d4bed-6d9b-4c14-9129-d7d3f0495501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Asuransi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Asuransi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fa7ca4b-fbe2-4dff-a5b9-e7ec3fe69b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aece7b72-2877-48c9-a58c-e169f8d7ce6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi</value>
      <webElementGuid>4b82ed1d-53d8-4964-9d5e-0d430ffcfe69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Asuransi</value>
      <webElementGuid>1551bc8a-a09d-4b03-aa36-9f3dc58a725f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Asuransi&quot;)</value>
      <webElementGuid>d553ab72-36f8-44d8-8fc1-ffb453c4bb37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Asuransi']</value>
      <webElementGuid>7b0929af-3b20-45e8-961e-ea11c3640883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c4671809-539c-4934-93d2-ffc9fde4e0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>9aed47d5-57b2-489f-b5e2-5568b8d1182d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Asuransi' and @id = 'gs_Asuransi']</value>
      <webElementGuid>632323ce-a88c-4c0f-8184-3fad48fa76ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
