<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_Asuransi</name>
   <tag></tag>
   <elementGuidId>bc533049-2878-4eb3-b6c6-e4695a04a38f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jqg1_Asuransi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jqg1_Asuransi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e74e9ea-dd09-4761-9ced-6f00be0353e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6570458-59a1-43d9-9f37-97fe9f189b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg1_Asuransi</value>
      <webElementGuid>494a548e-ac7a-4917-a446-4282170703ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi</value>
      <webElementGuid>2f9f57ad-8c89-4fe8-83de-24d2396ba5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4bb5f039-6f7a-4125-b1e3-47fbf9d60056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>068d0ff1-c53e-4445-8107-e962cd914937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg1_Asuransi&quot;)</value>
      <webElementGuid>55121a24-0c6d-4c6a-9298-f5d7e8877af0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg1_Asuransi']</value>
      <webElementGuid>5027314a-6f8e-41dd-8598-64607c393cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg1']/td[2]/input</value>
      <webElementGuid>705b4217-a86c-441f-84c6-ae9c51190fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>6b39aa20-c6ac-4d2b-9b64-6012d997d6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg1_Asuransi' and @name = 'Asuransi']</value>
      <webElementGuid>f61dc9b6-4be8-404c-b802-e3bc761c916d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
