<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_Fasilitas</name>
   <tag></tag>
   <elementGuidId>33307de7-88a9-4373-9283-d4baf731466d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jqg2_Nama_Fasilitas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jqg2_Nama_Fasilitas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1c1d720-2df0-44ea-a343-a58510b5cf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff6dcef7-6f4c-4076-93cb-6dd998b875ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_Nama_Fasilitas</value>
      <webElementGuid>cc21524b-8772-4551-b5f2-c215b87a0acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nama_Fasilitas</value>
      <webElementGuid>d2fd8886-67be-4d97-bf30-ac2180340d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>dfd681f0-9733-4383-bf26-c83ce48e12bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>4abd4f6c-fa9d-4472-833d-0589a69c4ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_Nama_Fasilitas&quot;)</value>
      <webElementGuid>235d1fc4-bfa1-4f1d-be4d-7b9a06531da5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg2_Nama_Fasilitas']</value>
      <webElementGuid>75058adb-4611-4ba3-86e9-697a64a6fd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg2']/td[2]/input</value>
      <webElementGuid>e058d801-d808-4de8-9ad6-fa990eb0a478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>fc4f661c-bd21-45a4-a0f5-df9a8b265926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg2_Nama_Fasilitas' and @name = 'Nama_Fasilitas']</value>
      <webElementGuid>082535b6-a875-44a0-b7c5-599882cdb5d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
