<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_Btn_Cetak</name>
   <tag></tag>
   <elementGuidId>a2cf820c-2553-418d-8bab-1f1e227d53ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;QRConvertInq('PJK2022100005')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.gridPrint > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>74b123a8-ed99-4097-beac-052097d00ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>QRConvertInq('PJK2022100005')</value>
      <webElementGuid>64fea60c-f2b3-46ba-b806-8bc88222dcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>1eb88f91-36e5-401d-ac93-b0a8f4dc4f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>a060ba33-2e5c-463f-a376-8ea824b3eb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cetak </value>
      <webElementGuid>31ac8824-aee3-4cb2-8446-3088567cc305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_editDetailIcon&quot;)/ul[@class=&quot;dropdown-menu pull-right&quot;]/li[@class=&quot;gridPrint&quot;]/a[1]</value>
      <webElementGuid>eb65f303-25a0-446f-8b73-cb28466b1c99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;QRConvertInq('PJK2022100005')&quot;]</value>
      <webElementGuid>31c3506c-303b-438d-985b-49fddc46da09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1_editDetailIcon']/ul/li[6]/a</value>
      <webElementGuid>edea0735-c039-4287-964c-77bef47a6bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cetak')]</value>
      <webElementGuid>5dea6891-1502-4b47-a734-f70931c6476c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Data'])[1]/following::a[1]</value>
      <webElementGuid>fa42f7c3-c33c-4116-b355-3ea5c28403cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[1]/following::a[2]</value>
      <webElementGuid>7b53c502-b451-4aba-9a86-ca8795eecbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yokoshita Dwi Purnomo, S.Kom.'])[1]/preceding::a[1]</value>
      <webElementGuid>5a3b0497-814e-4fd0-af97-45fc200c7bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yokoshita Dwi Purnomo, S.Kom.'])[2]/preceding::a[1]</value>
      <webElementGuid>ba12bdac-da5b-4f47-adec-36951dafe591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[8]</value>
      <webElementGuid>1f63a88f-5806-4118-ade4-d8541ecb64f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/ul/li[6]/a</value>
      <webElementGuid>10f16f76-0bb5-4a1b-bfcd-1104451eace0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Cetak ' or . = 'Cetak ')]</value>
      <webElementGuid>fcb47ff3-5c33-4601-8ed0-060a8df11ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
