<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_Btn_Ubah</name>
   <tag></tag>
   <elementGuidId>02ea942d-f9f4-4a26-823d-c14e4a247d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='RowHeaderEdit(1);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.gridEdit > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7f66f66-b94b-441a-945a-0db965958d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>e62d6a1a-4c04-485a-a19a-5f6854e50401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RowHeaderEdit(1);</value>
      <webElementGuid>d3a7d7f0-29ad-47b2-8bd1-e246839d7cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah </value>
      <webElementGuid>f8203fda-b510-4b00-b52c-693a24379ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_editDetailIcon&quot;)/ul[@class=&quot;dropdown-menu pull-right&quot;]/li[@class=&quot;gridEdit&quot;]/a[1]</value>
      <webElementGuid>82d7339a-8aef-4a26-b0f3-def4f3ceb719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='RowHeaderEdit(1);']</value>
      <webElementGuid>23531cde-86ba-449a-a839-d0cac41556ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1_editDetailIcon']/ul/li/a</value>
      <webElementGuid>516a3608-fcf4-452d-b662-e26da0b2f4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ubah')]</value>
      <webElementGuid>c8ba2e2f-e009-4d4b-b50c-ced672fa0282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disetujui'])[2]/following::a[1]</value>
      <webElementGuid>76c9c44a-b2a7-48b8-85f3-86513e30c688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[1]/following::a[1]</value>
      <webElementGuid>4b7580dd-6c1a-4b54-a842-cc53a6d65b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Data'])[1]/preceding::a[1]</value>
      <webElementGuid>be5bdef8-8461-4ea3-8c84-86cc6a12afef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[2]/preceding::a[2]</value>
      <webElementGuid>c25a22fd-5ffc-49b7-802b-d10b6269b1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>62177a49-9479-4b40-bfbc-8f0599d7d1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[6]</value>
      <webElementGuid>2e972dd2-7a7a-4d18-addc-a31577216fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/ul/li/a</value>
      <webElementGuid>3e902be6-45e2-4451-8340-d938ebd86290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Ubah ' or . = 'Ubah ')]</value>
      <webElementGuid>6a274869-6935-4066-af6f-1042f425140c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
