<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cetak</name>
   <tag></tag>
   <elementGuidId>0837bcd3-f53a-4246-a969-b64075fad5f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='QRConvert()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.green.btn-sm.btn-outline.btn-circle.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70a8e6ad-9e8b-43d5-bc57-b7487f0ff20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green btn-sm btn-outline btn-circle dropdown-toggle</value>
      <webElementGuid>076738c3-a080-4216-b1a0-69f9af769e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>QRConvert()</value>
      <webElementGuid>20178bc0-ea8b-4dc8-931e-72c7021fec17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>f3585403-a0be-4db6-9f41-3601d4ab9f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>776dc57b-5c45-4812-a536-e807c6867b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cetak
                                </value>
      <webElementGuid>a1730cf0-046b-45f1-a3a7-8ab33efc70b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PrintGlobal&quot;)/div[@class=&quot;btn-group&quot;]/a[@class=&quot;btn green btn-sm btn-outline btn-circle dropdown-toggle&quot;]</value>
      <webElementGuid>a0c05846-c65d-4cf8-84b3-1888b3dc0a8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='QRConvert()']</value>
      <webElementGuid>d969f0db-1533-45c3-a273-9730b63bde73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PrintGlobal']/div/a</value>
      <webElementGuid>d1b001f2-f002-4d83-8b7b-76e48b673117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cetak')]</value>
      <webElementGuid>ffd96763-8025-4733-bfe6-d091fcce3a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Cash'])[2]/following::a[1]</value>
      <webElementGuid>4402cb15-d8a8-4fdc-a698-6e2dd2afcc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View 1 - 50 of 106'])[1]/following::a[1]</value>
      <webElementGuid>42538548-bfff-4195-8d58-3d0001328413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Transaksi'])[1]/preceding::a[1]</value>
      <webElementGuid>c3fc5a4d-0d2d-4cc7-81cc-ead55b2b5872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Pengajuan'])[2]/preceding::a[1]</value>
      <webElementGuid>0156b6b4-ba45-4b9d-905a-5df1f924e440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[106]</value>
      <webElementGuid>ce3d08aa-ad4a-4d56-9a1f-144d68c0f37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/a</value>
      <webElementGuid>1602f479-0050-4c04-949e-5669ac9080af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Cetak
                                ' or . = 'Cetak
                                ')]</value>
      <webElementGuid>4707001f-e80c-4c7a-a7f0-dde605f5fc9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
