<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_TipePengajuan</name>
   <tag></tag>
   <elementGuidId>a10c72db-03f1-4d7b-b038-55c755eb9434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_TipePengajuanDesc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_TipePengajuanDesc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3493c707-1157-4aca-ac81-2dc9baa2eb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c49c1cf7-82a8-477e-b357-2e2f1ef3f63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TipePengajuanDesc</value>
      <webElementGuid>878c6f58-7a08-417b-8a62-1c6dcad8eb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_TipePengajuanDesc</value>
      <webElementGuid>91d99bcf-6a69-4804-a196-9e1474183b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_TipePengajuanDesc&quot;)</value>
      <webElementGuid>4ecf98e1-9d00-4bc7-846b-66b4a1bae659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_TipePengajuanDesc']</value>
      <webElementGuid>6feeb21b-48b6-4b64-a4ea-f4c083a7ce3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>3c7c2db0-0888-4e32-ae76-db882889946f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>1f6a61f8-cbb9-40fa-8bdf-db055f0c82c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TipePengajuanDesc' and @id = 'gs_TipePengajuanDesc']</value>
      <webElementGuid>bd5edbf5-f353-43c8-a040-c888518ac5a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
