<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Departemen</name>
   <tag></tag>
   <elementGuidId>68098432-8f4a-4e09-aaa4-42c94e9a3040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_NamaDepartemen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_NamaDepartemen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cddba64-6400-4f24-b284-5e4cf1bd112a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76dba217-9567-4559-b77e-5eb4a5544104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NamaDepartemen</value>
      <webElementGuid>d3c0a5db-5cab-4a34-9244-486988125ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_NamaDepartemen</value>
      <webElementGuid>6341a823-e92e-4a13-a3c2-d88fad07c47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_NamaDepartemen&quot;)</value>
      <webElementGuid>360ad167-c966-47f8-83a4-4b3fbd14b20e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_NamaDepartemen']</value>
      <webElementGuid>1529fe19-f69c-4bef-91df-10f2fa23699a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[5]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>14812e92-d824-4bb5-b181-d0e5a4d66f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>82048621-5feb-4a25-9ee6-2544f6245c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NamaDepartemen' and @id = 'gs_NamaDepartemen']</value>
      <webElementGuid>966af3bc-02fb-43da-a0f9-b341bef35aa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
