<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_NilaiPengajuan</name>
   <tag></tag>
   <elementGuidId>ca7e636c-11e2-44ff-8d65-587ed09fcfe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_NilaiPengajuan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_NilaiPengajuan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>782d116b-2870-4c13-98e6-be2ce9b149ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1794dbbe-9f17-4f2c-bbeb-3dae16fed014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NilaiPengajuan</value>
      <webElementGuid>7b0e8708-5e38-41a1-8955-a4a76519b5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_NilaiPengajuan</value>
      <webElementGuid>2eeba98d-56ec-48dd-8664-1d755623a629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_NilaiPengajuan&quot;)</value>
      <webElementGuid>dae5179a-bea3-4f01-b03c-705206df597f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_NilaiPengajuan']</value>
      <webElementGuid>97dbf161-9eef-4e02-80e6-191713b0f498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[8]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>14d5a47f-e434-43dc-9377-a778ca9762cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>88a40d7b-5c9f-4510-8a3a-d7235066d3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NilaiPengajuan' and @id = 'gs_NilaiPengajuan']</value>
      <webElementGuid>e8f440ce-d344-4450-8fa1-36d0620415d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
