<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_NIKNama</name>
   <tag></tag>
   <elementGuidId>a04be413-79fd-4f52-a690-8899a17713c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_NIKNama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_NIKNama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d26603e-7e7c-4b9e-b980-a44fc36e4e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3f7e8a7-670c-490a-9a5f-ecdd056a98d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NIKNama</value>
      <webElementGuid>88e800fa-94b1-4704-8771-8b08670ed6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_NIKNama</value>
      <webElementGuid>d688b592-4f78-4763-a735-1565c62d43fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_NIKNama&quot;)</value>
      <webElementGuid>12a2ca34-a914-4258-87d0-8cea5a3d4662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_NIKNama']</value>
      <webElementGuid>2b7fc599-7f5d-4697-b4d5-968769c1d550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>52272a4c-b3bf-4374-b778-5c749c4f1f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>31400f85-ffbd-41e1-826d-3e3bf4f1bd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NIKNama' and @id = 'gs_NIKNama']</value>
      <webElementGuid>15960efa-0fb7-40ed-a297-18568ba7c902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
