<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_MU</name>
   <tag></tag>
   <elementGuidId>d90b8906-8881-4df0-a01e-7694df56d423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_MU']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_MU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f3a5105-aad9-4c77-91de-51240b0e914b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00458808-9502-404f-bdd7-845aed39fafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MU</value>
      <webElementGuid>e1c1b7d4-fe46-4f59-a852-33bedc7f8f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_MU</value>
      <webElementGuid>9f5c3fe7-da7a-463f-9c80-3b3b0d9cc97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_MU&quot;)</value>
      <webElementGuid>d2cf68ae-c268-466c-a17e-9b814d6f1f5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_MU']</value>
      <webElementGuid>d7054f86-a26a-4d46-8aaa-3ae69d04a336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[7]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>edd01fd2-d7c4-4bf0-85ac-bb2d693b808e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>576d0cc8-cc66-4ba8-b92e-57a41279ab97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'MU' and @id = 'gs_MU']</value>
      <webElementGuid>d28aee49-2068-4cec-90a7-4cad07e229b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
