<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Keterangan</name>
   <tag></tag>
   <elementGuidId>cfbb5d30-9a1e-4b6c-846e-0c493c721a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Keterangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_Keterangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9b94378-592e-4254-9f4f-0c99d24d431e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3383cd03-6652-4d85-a99a-3af79a4e70c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>cb33521d-5e8f-439e-83be-fe267a24964d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Keterangan</value>
      <webElementGuid>e277eb00-170b-4c85-a9b9-5906e36ef1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Keterangan&quot;)</value>
      <webElementGuid>30b5de13-f329-4082-a478-da9ceef85506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Keterangan']</value>
      <webElementGuid>a1a2fd03-bc38-45ee-823d-3df06166d10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[6]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f3116adc-640e-46ae-a590-3e0e2e4709fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>9e81cea3-6fbf-4e3c-9d4e-9779b9e09f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Keterangan' and @id = 'gs_Keterangan']</value>
      <webElementGuid>151060a3-4e48-431d-9dec-66c64e2595fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
