<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Catatan</name>
   <tag></tag>
   <elementGuidId>ee61b03a-792d-4d15-8f46-4de1b3e2ba01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='inputAlasan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputAlasan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f5e18907-6496-431d-8b8e-3b26d6af1b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2f1958fa-96f8-4efe-a913-ae2b00703ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAlasan</value>
      <webElementGuid>432b8276-e143-4b34-9fb4-5455637d2953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>71860a04-7b5c-425d-bf16-e9cb30e92b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tujuan Pengajuan</value>
      <webElementGuid>8c117181-09f7-4f62-a235-0f39f348f3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAlasan&quot;)</value>
      <webElementGuid>7df4ee84-ceec-482e-b7fb-abf7617c04d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='inputAlasan']</value>
      <webElementGuid>c4b26417-68eb-4fb7-bbd4-9d2749948074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectiondetail']/div/div[2]/div/div/div[12]/div/div/textarea</value>
      <webElementGuid>0c367030-fc5b-4e16-9097-5e58cec08085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6a2537ab-44b9-4c55-97d0-a35b95e42d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'inputAlasan' and @placeholder = 'Tujuan Pengajuan']</value>
      <webElementGuid>f6ea14e7-aed9-4c57-b012-5445157adff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
