<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalTransaksi</name>
   <tag></tag>
   <elementGuidId>8d2157fb-9b96-48de-bde2-ac3aa2900337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tanggalTransaksi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tanggalTransaksi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d5ac29d-0b54-412a-abcb-0a2893f18cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>766233b3-b0db-47bf-bf96-20a2c08117c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>23470e56-ea84-40f1-8a03-b70734f5b802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tanggalTransaksi</value>
      <webElementGuid>fe1fb880-fafc-481b-9e00-52a4c53b64af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD-MMM-YYYY</value>
      <webElementGuid>cba2d8e7-90d2-4458-be4f-6bcdd0a0950f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tanggalTransaksi&quot;)</value>
      <webElementGuid>7442fb08-38b5-4a2d-8b27-17fe36a420c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tanggalTransaksi']</value>
      <webElementGuid>608c57d4-0318-4c10-89ae-e0e3272068f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectiondetail']/div/div[2]/div/div/div[6]/div/div/input</value>
      <webElementGuid>080d14c9-ba25-4575-bc26-233c809ca83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>97e88cdb-b11c-447d-841c-1b8264c4b458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tanggalTransaksi' and @placeholder = 'DD-MMM-YYYY']</value>
      <webElementGuid>7a07a106-5519-4603-bc07-adb3b9b3b5f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
