<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoTransaksi</name>
   <tag></tag>
   <elementGuidId>230793d5-9719-44ec-bf16-8d7e019e12dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sectiondetail']/div/div[2]/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b9cb524-6831-48d0-b28b-7fc2a7919abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-4</value>
      <webElementGuid>8ab05940-443c-4d67-a198-084320677aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectiondetail&quot;)/div[@class=&quot;portlet light bordered&quot;]/div[@class=&quot;portlet-body form&quot;]/div[@class=&quot;form-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group form-md-line-input&quot;]/div[@class=&quot;col-md-4&quot;]</value>
      <webElementGuid>e256682c-194d-4106-ad56-0d67512cbb97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectiondetail']/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>3e98b735-dfbf-4d59-8158-83778f5d973c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Transaksi'])[1]/following::div[1]</value>
      <webElementGuid>823b50ba-0207-4072-884b-5f77dfe93e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak'])[5]/following::div[6]</value>
      <webElementGuid>5ad0049b-e9a5-4fc4-a2a9-87aaeb85498a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Pengajuan'])[2]/preceding::div[3]</value>
      <webElementGuid>833604b8-1f3f-4486-99fc-dca4fc2cdc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>6c5c668f-35af-4405-bb3b-ada8693791da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
