<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_DeleteFile</name>
   <tag></tag>
   <elementGuidId>b3787018-cac9-4b9a-a1fe-2fe39acc41c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@onclick='DeleteDokumen(&quot;216bc6a1-75e4-4d45-9fca-3b161e8ffc6b&quot;)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-close.DelDocKTKP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ae54cc40-cf82-4548-96ed-e965f5255fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-close DelDocKTKP</value>
      <webElementGuid>61a246c9-baf7-4e53-8570-59f573e41574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DeleteDokumen(&quot;216bc6a1-75e4-4d45-9fca-3b161e8ffc6b&quot;)</value>
      <webElementGuid>24971105-0c59-4161-aec3-e29e6a82331f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete file</value>
      <webElementGuid>5c8c85da-8ff9-4d9e-8388-37ea9a74997e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dvDocKTKPSlider&quot;)/div[@class=&quot;wrapper&quot;]/i[@class=&quot;icon fa fa-close DelDocKTKP&quot;]</value>
      <webElementGuid>7a9285e5-c7d4-40a3-aa63-2ff021caecda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@onclick='DeleteDokumen(&quot;216bc6a1-75e4-4d45-9fca-3b161e8ffc6b&quot;)']</value>
      <webElementGuid>e04d80f0-9a24-4f33-b4c2-2462eb4fb49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvDocKTKPSlider']/div[2]/i</value>
      <webElementGuid>8c178059-bcf6-427a-acb3-763f9dd8c29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>ed79ecec-c49e-408a-a23d-afc623acd18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Delete file']</value>
      <webElementGuid>c99479b6-66f7-44ec-ae56-0a8168ca702f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
