<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PersetujuanStatus</name>
   <tag></tag>
   <elementGuidId>ddb81734-59bb-42bf-957f-22c9e9a83c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gs_StatusAppr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_StatusAppr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d817142d-2947-4852-8321-0feed1d6188b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StatusAppr</value>
      <webElementGuid>69e0fdb0-cdf8-49a1-9699-8dab235ea589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_StatusAppr</value>
      <webElementGuid>d59d7730-4ce9-448a-9ac2-95f6c245df8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllDitolakBelum DipostingDisetujuiDalam ProsesPostedClosedBelum ada pertanggungjawabanPertanggungjawaban Belum Penuh</value>
      <webElementGuid>18bff777-a671-4d8e-a75c-2a166523ccff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gview_MainGrid&quot;)/div[@class=&quot;ui-state-default ui-jqgrid-hdiv&quot;]/div[@class=&quot;ui-jqgrid-hbox&quot;]/table[@class=&quot;ui-jqgrid-htable&quot;]/thead[1]/tr[@class=&quot;ui-search-toolbar&quot;]/th[@class=&quot;ui-state-default ui-th-column ui-th-ltr&quot;]/div[1]/table[@class=&quot;ui-search-table&quot;]/tbody[1]/tr[1]/td[@class=&quot;ui-search-input&quot;]/select[@id=&quot;gs_StatusAppr&quot;]</value>
      <webElementGuid>2e6e5f86-d419-4ace-a3fc-f4022394c059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gs_StatusAppr']</value>
      <webElementGuid>865cd864-191d-4520-aa08-274e69c18355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[10]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>3ec9e38c-12c8-4ae5-a848-09f8edba6af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[8]/following::select[1]</value>
      <webElementGuid>a737b4dd-1d78-4c20-bf1e-ace30f544c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[7]/following::select[2]</value>
      <webElementGuid>4a9896d7-c100-4f8d-9e74-711ad0077ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[9]/preceding::select[1]</value>
      <webElementGuid>62205979-367d-45dc-a3e9-943b0d798579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[10]/preceding::select[1]</value>
      <webElementGuid>d948833d-2bee-4969-aa70-839cec9b61b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[10]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>a56a046a-899a-4e65-96ac-60c64def4167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'StatusAppr' and @id = 'gs_StatusAppr' and (text() = 'AllDitolakBelum DipostingDisetujuiDalam ProsesPostedClosedBelum ada pertanggungjawabanPertanggungjawaban Belum Penuh' or . = 'AllDitolakBelum DipostingDisetujuiDalam ProsesPostedClosedBelum ada pertanggungjawabanPertanggungjawaban Belum Penuh')]</value>
      <webElementGuid>3b7fa5d9-c5ab-417f-9450-25bb860d6519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
