<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Status</name>
   <tag></tag>
   <elementGuidId>ae2b7550-43b1-45c0-a12e-7813b009af98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gs_Status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_Status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b34c1c79-7446-4260-a7c0-5bef22f47e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>79498d5b-228e-464a-8aa0-b0b2f6f256f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Status</value>
      <webElementGuid>26723a87-0bb9-4b43-90ef-cd5eee1ce268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllActiveNon Active</value>
      <webElementGuid>98b5f488-1e11-4a00-a027-ff4899a28378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gview_MainGrid&quot;)/div[@class=&quot;ui-state-default ui-jqgrid-hdiv&quot;]/div[@class=&quot;ui-jqgrid-hbox&quot;]/table[@class=&quot;ui-jqgrid-htable&quot;]/thead[1]/tr[@class=&quot;ui-search-toolbar&quot;]/th[@class=&quot;ui-state-default ui-th-column ui-th-ltr&quot;]/div[1]/table[@class=&quot;ui-search-table&quot;]/tbody[1]/tr[1]/td[@class=&quot;ui-search-input&quot;]/select[@id=&quot;gs_Status&quot;]</value>
      <webElementGuid>0bb6a100-a65e-4a45-9fe1-b755531be87e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gs_Status']</value>
      <webElementGuid>797ae53b-fc1c-4597-87f9-b1d5bf290660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[9]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>a27dcb63-fdd4-4409-9411-96a2e4c9742b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[7]/following::select[1]</value>
      <webElementGuid>7f3c7bd5-80a7-48f1-bbfe-9544370623a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[6]/following::select[1]</value>
      <webElementGuid>8674945a-d75d-4252-ae8b-46c3dfd62b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[8]/preceding::select[1]</value>
      <webElementGuid>249d58d2-10dd-4c1e-b922-32df59b7ff51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[9]/preceding::select[2]</value>
      <webElementGuid>dc9d685f-e18f-4b05-88be-554669b808ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>cb7d8512-9bda-4baf-ae01-fb126b5dcfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Status' and @id = 'gs_Status' and (text() = 'AllActiveNon Active' or . = 'AllActiveNon Active')]</value>
      <webElementGuid>5a5622bc-4e7b-47e6-bd14-88cece4f1d61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
