<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tipe_Pengajuan_Pinjaman Dinas_check</name>
   <tag></tag>
   <elementGuidId>b697421f-e27c-474d-9e64-229f61535a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pinjamanDinas']/div/label/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e8304d7-ad7c-4bfd-a095-201747034d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>10c35fa5-76f6-4511-8795-e4881a93c531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pinjamanDinas&quot;)/div[@class=&quot;md-radio&quot;]/label[1]/span[@class=&quot;check&quot;]</value>
      <webElementGuid>4f6b42c9-c1ec-484c-91c4-0987c296c475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pinjamanDinas']/div/label/span[2]</value>
      <webElementGuid>511d2ec1-11e4-45b1-b566-63f3fc06b40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span[2]</value>
      <webElementGuid>c4a53083-caa0-4ca3-bae9-6002ccf96b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
