<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tipe_Pengajuan_Reimburse_check</name>
   <tag></tag>
   <elementGuidId>e18367d4-c4f3-4c2d-a691-1299bdf45ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pinjamanDinas']/div[2]/label/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6599bdcf-ec9f-471a-8f96-232b652235ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>e8d726c4-f8a2-4de4-8276-b8b0c6dd6d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pinjamanDinas&quot;)/div[@class=&quot;md-radio&quot;]/label[1]/span[@class=&quot;check&quot;]</value>
      <webElementGuid>a1eaf9f2-a083-4f91-a261-9b4339185f24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pinjamanDinas']/div[2]/label/span[2]</value>
      <webElementGuid>4eabf1cb-a35e-436b-8bad-5544ba96561b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span[2]</value>
      <webElementGuid>e16e9a89-ea66-4781-93e4-e22ae449020f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
