<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_btn_Search</name>
   <tag></tag>
   <elementGuidId>ac721f1f-4e7d-4208-a6ef-7355be974ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='1_editIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.fa-ellipsis-h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27966f6d-8175-4e9f-9831-a4c9a4afa25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_editIcon</value>
      <webElementGuid>193884bd-69ca-451d-976e-c6e788d09dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-h</value>
      <webElementGuid>8989da16-7cbe-4ce9-9473-d41468c06afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doEdit(1);return false;</value>
      <webElementGuid>93bdc93a-9f00-49e6-a919-750616d56cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_editIcon&quot;)</value>
      <webElementGuid>5fb133b5-83bd-4069-9cd6-89b5a65918f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='1_editIcon']</value>
      <webElementGuid>1d03d6e3-111d-40cc-a75b-cf650b9290f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[32]/span</value>
      <webElementGuid>33fa363d-4a66-4e76-a760-6944f6e2f33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[32]/span</value>
      <webElementGuid>cade0f55-6080-4e9b-9ead-e88d8bb9bd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '1_editIcon']</value>
      <webElementGuid>e7f7acb0-3e48-4a30-bf0c-a03e7776a224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
