<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_Btn</name>
   <tag></tag>
   <elementGuidId>c3d8269c-493d-4285-97e4-deb78f7af860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='groupBtn1']/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#groupBtn1 > button.btn.btn-xs.green.dropdown-toggle > i.fa.fa-ellipsis-h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9f9f4c29-9b19-460d-9e0c-ad9145e37980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-h</value>
      <webElementGuid>0a960508-666f-4149-9d7a-7daf84f94291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupBtn1&quot;)/button[@class=&quot;btn btn-xs green dropdown-toggle&quot;]/i[@class=&quot;fa fa-ellipsis-h&quot;]</value>
      <webElementGuid>01414da4-a893-4ffb-b9e0-c8540ae89375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupBtn1']/button/i</value>
      <webElementGuid>7dad059e-8343-4404-85d7-4f9af5409344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[3]/div/table/tbody/tr[2]/td[5]/div/button/i</value>
      <webElementGuid>50aadb10-bef3-4897-ae83-6635e8604a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
