<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_btn_Hapus</name>
   <tag></tag>
   <elementGuidId>a0b4d7eb-20d9-43a9-8a12-47ac530a5a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='1_deleteComplainIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1_deleteComplainIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>559b691b-6888-4e32-ab5f-75f85155f644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_deleteComplainIcon</value>
      <webElementGuid>f10bbab7-b6d0-4da6-9794-4431aea6a5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>ff2c28b2-b878-4315-b9c6-a6231344aabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RowComplainDelete(1);</value>
      <webElementGuid>87bc18a9-4a04-4db7-97a1-57d00e370138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus </value>
      <webElementGuid>42823a93-4b64-4fe0-80ef-a626bcf4a89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_deleteComplainIcon&quot;)</value>
      <webElementGuid>665da4c7-3d37-4d26-a84d-ae087718e986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='1_deleteComplainIcon']</value>
      <webElementGuid>74c81e7f-c1c1-4cb6-b3a3-964efabb6968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupBtn1']/ul/li[3]/a</value>
      <webElementGuid>1cc6109e-7ba3-49d0-8de7-f35b43a46e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Hapus')])[2]</value>
      <webElementGuid>e76a6e57-f7c6-41d5-a336-d1905adf4b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[2]/following::a[1]</value>
      <webElementGuid>d644859b-c9b4-4fa5-b603-1ffa50271e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL'])[2]/following::a[2]</value>
      <webElementGuid>3198ac5a-700e-4f14-bc49-7600d8372d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View 1 - 1 of 1'])[2]/preceding::a[1]</value>
      <webElementGuid>de577b03-31c3-411e-ba3a-5d16862c1229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[21]</value>
      <webElementGuid>18b949de-75e2-4123-95cf-32867e4b4042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[3]/div/table/tbody/tr[2]/td[5]/div/ul/li[3]/a</value>
      <webElementGuid>4fcbd180-00aa-463c-808a-9ee768391a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '1_deleteComplainIcon' and @href = 'javascript:;' and (text() = 'Hapus ' or . = 'Hapus ')]</value>
      <webElementGuid>224a117c-8359-437e-a1e4-ac4fb19e9d80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
