<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action_btn_Ubah</name>
   <tag></tag>
   <elementGuidId>d6012b1c-455d-454e-a868-e12b0f4766f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='1_editComplainIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1_editComplainIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a97e8114-914d-411b-949a-ba46848a822e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_editComplainIcon</value>
      <webElementGuid>dd306775-e195-4bf6-8a66-9c9b42de0d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>232f229b-6e53-46b6-a674-70b6c071d7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RowComplainEdit(1);</value>
      <webElementGuid>5686eaa6-6f4b-441e-8cd0-3c52d0847bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah </value>
      <webElementGuid>8716cab6-ec13-4f9b-b673-9b4bd3b16d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_editComplainIcon&quot;)</value>
      <webElementGuid>65637f9f-3daa-4843-9a61-1eee7bfd17e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='1_editComplainIcon']</value>
      <webElementGuid>c0f4f275-f661-4fc4-98f5-ba9bda3bd286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupBtn1']/ul/li/a</value>
      <webElementGuid>eb48cc5d-b0b0-400c-bb42-48e6af31a7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ubah')])[2]</value>
      <webElementGuid>c488739c-455a-416f-9d6a-a13dae9fa8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL'])[2]/following::a[1]</value>
      <webElementGuid>897ad9d8-2f53-4365-86c4-ee58d7cd3f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lantai granito/ keramik terangkat'])[1]/following::a[1]</value>
      <webElementGuid>888f1867-9481-4b76-85cd-fb0d45868785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[2]/preceding::a[1]</value>
      <webElementGuid>a359ddd3-6735-49e9-a5ee-fbf6b3cbd586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[20]</value>
      <webElementGuid>7f02e348-d0b5-4990-9275-8dba6187666f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[3]/div/table/tbody/tr[2]/td[5]/div/ul/li/a</value>
      <webElementGuid>730c30b9-00fe-4287-b1b8-c310dbc65913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '1_editComplainIcon' and @href = 'javascript:;' and (text() = 'Ubah ' or . = 'Ubah ')]</value>
      <webElementGuid>d47472c1-629d-4e0b-a3e8-6ed31c4fc567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
