<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DDL_Item</name>
   <tag></tag>
   <elementGuidId>327e9590-9994-4438-902d-dfe54d36649e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='MainGridDetail']//span[@class='select2-chosen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby='MainGridDetail_Nama_Spec'] .select2-choice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85f697cb-f7a5-4313-97e1-e5757066485d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-chosen</value>
      <webElementGuid>481e7529-acd5-47dc-9c08-89f49eac1937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MOCK UP</value>
      <webElementGuid>a8365cb1-7680-479b-bc60-9cdc165aaf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s2id_jqg2_Nama_Spec&quot;)/a[@class=&quot;select2-choice&quot;]/span[@class=&quot;select2-chosen&quot;]</value>
      <webElementGuid>8e3869ad-fbc5-49ce-b721-fbddf75bde25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s2id_jqg2_Nama_Spec']/a/span</value>
      <webElementGuid>f3620cea-ba5d-47be-aaf2-d775c83e8dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode_Aktivitas'])[1]/following::span[2]</value>
      <webElementGuid>ff4b18cd-0478-475d-8623-451edf11fee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDDetailRPT'])[1]/following::span[6]</value>
      <webElementGuid>4c4f4b7d-a503-45d5-a7de-8676a18c9b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[1]/preceding::span[2]</value>
      <webElementGuid>2102a848-b3f1-49e4-84d2-c4299c38c4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::span[2]</value>
      <webElementGuid>3aff9899-752a-45b8-aed3-e59086b1e88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MOCK UP']/parent::*</value>
      <webElementGuid>f4bad24a-1dea-4147-941e-1cb19f1785cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a/span</value>
      <webElementGuid>67a459e1-2ad0-4f13-9873-1fdd2481db7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MOCK UP' or . = 'MOCK UP')]</value>
      <webElementGuid>7692c125-2e0e-4bd5-a001-5833663596d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
