<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan</name>
   <tag></tag>
   <elementGuidId>12a142fb-69db-4633-a06b-38e199c17157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='jqg2_Keterangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg2_Keterangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c9b5d239-7e24-4610-aa59-c605ea73bf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_Keterangan</value>
      <webElementGuid>9c4efe15-b8b3-4528-bf73-f4b4812c2491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b8b8e680-9a4e-4d29-a343-49e0eafc8b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f760cb8-5dbf-4c82-b21b-b4207b5e8205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_Keterangan&quot;)</value>
      <webElementGuid>1fbc176e-619f-47e7-8be8-d46ccd2d9099</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='jqg2_Keterangan']</value>
      <webElementGuid>91c3afc4-e62a-473b-bfac-4eeea50c7ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainGridDetail_jqg2']/div/div[2]/div[3]/div/div/div/textarea</value>
      <webElementGuid>1fc6d70d-4fcc-4be8-ab24-96f313237b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>423ef35d-c7a3-485e-a226-e637ec622f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'jqg2_Keterangan' and @type = 'text']</value>
      <webElementGuid>9142969c-900a-48af-b432-fb80267ad695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
