<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan</name>
   <tag></tag>
   <elementGuidId>12a142fb-69db-4633-a06b-38e199c17157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='panel form-horizontal']//div[@class='col-sm-8']/textarea[@class='form-control']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2cad3b0b-f122-4bab-94e6-5f2cb897efdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_Keterangan</value>
      <webElementGuid>0b7e9ba8-af84-46bd-a2e7-be0634ffb641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3487cba-b855-41ea-b2c6-85b5a503e73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2a5010e-5136-4f48-b204-cbf2aae0809e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_Keterangan&quot;)</value>
      <webElementGuid>3107d8ee-9f2c-469e-b6e7-3c2e7a51e079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='jqg2_Keterangan']</value>
      <webElementGuid>d18ccb8a-d381-4a14-a021-c21660fe0290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainGridDetail_jqg2']/div/div[2]/div[3]/div/div/div/textarea</value>
      <webElementGuid>99c778f1-acfa-4c57-8355-215d5b519683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a8b24870-6468-477e-a513-3f63f95f3fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'jqg2_Keterangan' and @type = 'text']</value>
      <webElementGuid>2d4fb648-27cd-404b-98b5-c444a6014436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
