<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_no_biaya_umum</name>
   <tag></tag>
   <elementGuidId>c798cac5-7ee7-4ffc-a56d-6be0598602b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Gen_Cost_Code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_Gen_Cost_Code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc388478-f6df-46a7-9a2e-4573ea6a6bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8234e14a-add1-4706-97d3-95cc8785649c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gen_Cost_Code</value>
      <webElementGuid>5b6440a1-0312-49ef-aee1-ab07f27fba2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Gen_Cost_Code</value>
      <webElementGuid>cfa59e30-bb29-4204-9f93-7961784982a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Gen_Cost_Code&quot;)</value>
      <webElementGuid>cef2ef06-6794-4841-be81-c20b826a556c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Gen_Cost_Code']</value>
      <webElementGuid>fea0da35-e8a7-4f4e-b0c4-f13e24b24a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>7ea532f9-8af6-417f-a117-56eb919c102e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>7ef8922f-c5e7-400f-8b27-8746d0b5e591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Gen_Cost_Code' and @id = 'gs_Gen_Cost_Code']</value>
      <webElementGuid>427c59d1-2229-4659-a8c7-ca78f8781964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
