<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit Price</name>
   <tag></tag>
   <elementGuidId>8bbce0fc-db79-4e35-84c6-ad78b38ee2b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='panel form-horizontal']/div[@class='panel-body text-left']/div[2]//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.form-horizontal.panel > .panel-body > div:nth-of-type(2) [name='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5453ce66-f291-4fda-baa0-2df32a124f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_Unitprice1</value>
      <webElementGuid>0329b246-64bf-4bc5-81b9-58a2c416d4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>20bb20a7-413b-4c18-9ab2-aedcab1b5d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ba6dbbd-7e67-49b7-8eb1-35e0211f2ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a4d1e6b-a140-4408-92b8-c1dce3f097ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_Unitprice1&quot;)</value>
      <webElementGuid>39d85940-b8bd-4c41-9404-e8d528f19135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg2_Unitprice1']</value>
      <webElementGuid>9c186b6a-882c-4bdf-8961-2fc748ef2b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainGridDetail_jqg2']/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>a862c2a3-80fb-4ff3-942b-3608f1611e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>5757e195-bcb9-41f7-905b-d3a31d1b10b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jqg2_Unitprice1' and @name = 'name' and @type = 'text']</value>
      <webElementGuid>6f43caee-cfc3-48bf-97dc-d86b39d6753c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
