<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Jumlah_Biaya_Complain</name>
   <tag></tag>
   <elementGuidId>0e72e943-023b-4ac5-afd2-1da1b16a1fb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtJumlahBiayaComplain']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtJumlahBiayaComplain</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7209207-09ba-4d1f-a877-73b441fd51b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>536bfb60-90ef-4c59-8727-2c5eeaf50e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-right</value>
      <webElementGuid>31a4b4e5-e0bd-4aac-8e38-2558cb4da487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtJumlahBiayaComplain</value>
      <webElementGuid>4522fc58-32b6-4ecd-9753-23160d6503d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtJumlahBiayaComplain&quot;)</value>
      <webElementGuid>baf9cced-1411-4c04-8139-834fbb4abb5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtJumlahBiayaComplain']</value>
      <webElementGuid>33ea0ca6-2234-4338-b168-89e77fa83465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvCC']/div[3]/div/div/input</value>
      <webElementGuid>74b35d75-3e53-4f68-8e25-12df60cb6f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div/input</value>
      <webElementGuid>4b034d4c-e3af-44dc-905c-b8adb0862600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtJumlahBiayaComplain']</value>
      <webElementGuid>789cdea3-d4cb-4de2-9b4b-13569041c62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
