<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Biaya_Complain_input_Jumlah</name>
   <tag></tag>
   <elementGuidId>425bc79e-bef2-48fd-8c42-a4a6fab41c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='editable text-right']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg3_Jumlah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0da2bc3-a887-45c5-ad9f-72870842ed7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04f9fadc-76fd-47ee-9b47-41a0074a685a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg3_Jumlah</value>
      <webElementGuid>49b414b6-4f95-492d-9dfb-afc4534ec4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Jumlah</value>
      <webElementGuid>71a3ab0c-d508-4990-89ba-e18e7094d6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ffbb0a66-5769-4f76-8405-703c24a635c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable text-right</value>
      <webElementGuid>60622566-8a04-4394-b545-fffb02b4e1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg3_Jumlah&quot;)</value>
      <webElementGuid>7344ca51-4f6c-438d-9dd5-20889c8afd73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg3_Jumlah']</value>
      <webElementGuid>4d9bd456-0392-4cf6-bbc9-c6dd6c5125c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg3']/td[4]/input</value>
      <webElementGuid>994fc99a-e278-4c8a-a6e3-e53e6dbd4a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>cd227070-c30c-4ec4-80c6-a2119204159d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg3_Jumlah' and @name = 'Jumlah']</value>
      <webElementGuid>26b1c448-c8ed-4ad2-9371-8c2847c0da1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
