<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_BiayaComplain_btn_Tambah</name>
   <tag></tag>
   <elementGuidId>3d671e42-10f9-4489-95cb-3eb7ffb016ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAddComplain']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAddComplain</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66ddcc99-a2f8-47bb-b7d9-43190e9ef1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>f56b90fc-611c-4d80-aa44-e88aaaea7c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddComplain</value>
      <webElementGuid>17dbdc5f-3dc4-42cd-b39c-d3dcf354602f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>00754343-de85-4c0d-b304-132a1053282b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddComplain&quot;)</value>
      <webElementGuid>43819c4d-4f81-42ee-9b06-500562547c34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAddComplain']</value>
      <webElementGuid>9e8cb899-0301-4ec3-9fb0-cb9bf1d02233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvModalLantai-modal']/div/div[2]/div/button</value>
      <webElementGuid>c0bca4fe-d1cb-447c-ab56-44b236613fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaya Penanganan Complain'])[1]/following::button[1]</value>
      <webElementGuid>b4b00400-d91c-4828-8ad0-e908d6235467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/following::button[1]</value>
      <webElementGuid>22e57d76-03d4-4ee5-bd7e-e03f343f3171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading Data please wait ...'])[3]/preceding::button[1]</value>
      <webElementGuid>3da41ec4-094e-4a2e-abf4-76238d4e8c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No.'])[2]/preceding::button[1]</value>
      <webElementGuid>660e443a-d1c7-4de3-8aa1-fe527f3f1fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/button</value>
      <webElementGuid>031d1c4f-04bb-4006-b5c8-74199cc34ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnAddComplain' and (text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>3025cd71-19aa-49d0-9e60-6a7a4a624bb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
