<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Biaya_Complain_input_Jumlah</name>
   <tag></tag>
   <elementGuidId>425bc79e-bef2-48fd-8c42-a4a6fab41c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jqg3_Jumlah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg3_Jumlah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40053187-cb20-4de3-bbb6-1c3d8c0cbc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c209f200-b8cd-4d33-80ef-9304b8d5d508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg3_Jumlah</value>
      <webElementGuid>17f68c87-59c8-4d5a-b16d-eb2ba80eebf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Jumlah</value>
      <webElementGuid>ff9ee3bc-fcf5-4f85-a1c8-af889cb7f939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>27c21370-57be-4da3-9a7e-9f7dd4743c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable text-right</value>
      <webElementGuid>dec8ab59-b416-4e52-bd10-35f2c4eb556a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg3_Jumlah&quot;)</value>
      <webElementGuid>c95732b6-c2d5-4f4a-a9e5-78f74151a803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg3_Jumlah']</value>
      <webElementGuid>bda85681-6797-499b-9f64-013bb8435bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg3']/td[4]/input</value>
      <webElementGuid>43142c1f-ef16-493f-9333-a3a960625ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>94eb36be-c24f-43c3-a982-892ed3e659b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg3_Jumlah' and @name = 'Jumlah']</value>
      <webElementGuid>ae2b94b5-415f-40e2-86d2-48137c8996b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
