<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Biaya_Complain_DDL_Masalah</name>
   <tag></tag>
   <elementGuidId>3da3802b-fd22-4fbe-a802-5d251161594a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s2id_jqg3_Keluhan']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby='ComplainGrid_Keluhan'] .select2-chosen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>817a861e-7c64-40be-9c14-ac7bb8f5b294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-chosen</value>
      <webElementGuid>3793061f-ea7a-4d3a-9c9b-961b55bac09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2207A0D6D97D - Lantai beton retak/gompal</value>
      <webElementGuid>57aa95e4-50b7-4fcb-9eee-8317d97945db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s2id_jqg3_Keluhan&quot;)/a[@class=&quot;select2-choice&quot;]/span[@class=&quot;select2-chosen&quot;]</value>
      <webElementGuid>aa2a5be8-8e38-4795-b359-e71eefb31236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s2id_jqg3_Keluhan']/a/span</value>
      <webElementGuid>586b33a3-03b1-4990-88de-d7a7b383e429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[46]/following::span[1]</value>
      <webElementGuid>3ef34176-2f7e-425c-b4d5-9671d222ecd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[45]/following::span[1]</value>
      <webElementGuid>0b91f9cd-50c1-42dd-9973-910492a6367e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Pilih --'])[2]/preceding::span[2]</value>
      <webElementGuid>3e6f5824-c774-4254-9fab-1feb2b94e0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[2]/preceding::span[4]</value>
      <webElementGuid>2e293f3e-5c26-4b33-9262-ffd0486a746c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2207A0D6D97D - Lantai beton retak/gompal']/parent::*</value>
      <webElementGuid>2264d6ad-0351-487c-a2c0-a173c6c3f61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a/span</value>
      <webElementGuid>953f2736-99ad-4b66-b254-eb4e10efa700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2207A0D6D97D - Lantai beton retak/gompal' or . = '2207A0D6D97D - Lantai beton retak/gompal')]</value>
      <webElementGuid>0cd9a0c0-c773-4787-bf9d-9d819a340027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
