<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username</name>
   <tag></tag>
   <elementGuidId>cf28a319-e597-4edf-a312-219b3fa3d1ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#username_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac7ef2a5-cd06-49b4-a2fb-bfef7519191d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username_id</value>
      <webElementGuid>14e7d806-eab6-49ac-b9b5-8e71eea10690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>178804b7-71f1-47bf-bef7-0724e1fa32a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username_id</value>
      <webElementGuid>b5a984d6-bad3-43a8-b8c2-621cac2dee3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>dbff7967-c4f0-47e5-a0a5-bedfd6a18f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username or NIK</value>
      <webElementGuid>549bee50-18cd-4790-b9d8-ca0866261197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username_id&quot;)</value>
      <webElementGuid>b5d75986-8492-49e5-b698-cfd40db30774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username_id']</value>
      <webElementGuid>985d3bd6-3a72-4b76-bc55-c70febf16f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin_form_id']/div[2]/input</value>
      <webElementGuid>084c7594-16bf-4a9f-8a21-6ae7575d0167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f46e6f4b-36c8-4db5-8d67-b7079ceb3e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username_id' and @type = 'text' and @id = 'username_id' and @placeholder = 'Username or NIK']</value>
      <webElementGuid>41ba6c3c-8285-44bb-a135-f156bc2ad3b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
