<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>8eed3e27-becc-4fe8-a9ff-43bd7913ce9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5985e87-9712-4c89-889c-89320eb7b50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_id</value>
      <webElementGuid>b3ab32b5-4a4f-428c-b0c4-b7013dc96d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f038e084-2755-44cd-af67-0d92c0b5d47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_id</value>
      <webElementGuid>e1d1776d-2bfa-4956-a7ec-1a7cd503efe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>66da42f3-e238-44f0-8a78-90d4e7197ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>8ee969a5-4680-48ea-83a9-8a0eb7575777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_id&quot;)</value>
      <webElementGuid>e4e4a191-5ddd-4fcc-a52f-d829ddabb70c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_id']</value>
      <webElementGuid>384856a4-7113-41b3-bbc2-bf496a4aa7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin_form_id']/div[3]/input</value>
      <webElementGuid>8837eb3b-7952-4dff-bc24-8aa02fd187f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>774c4ba1-e2fe-467a-90bc-be93fd4aabdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password_id' and @type = 'password' and @id = 'password_id' and @placeholder = 'Password']</value>
      <webElementGuid>e922b797-e3f0-4226-89ca-c0e5f8f85775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
